### ISSUE TITLE
Companion App

### ISSUE THREAD

**Issue by 0x5ECF4ULT** [AKVorrat/istkicklschonweg.at#4]
Hey. Mit deiner / eurer Erlaubnis werde ich eine App gestalten und diese bei F-Droid einreichen. Die ist eine Richtlinie bei der Einreichung. Gleichzeitig würde ich dich / euch auch bei dem Projekt als Inhaber hinzufügen. :)

**Comment by meksor** [comment]
Meinen Segen hast du!

**Comment by 0x5ECF4ULT** [comment]
App almost finished:wink:
Schönes neues
